# Generated by Django 4.2 on 2024-12-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=40)),
                ('correo_electronico', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=40)),
                ('escribrenos', models.CharField(max_length=400)),
            ],
        ),
    ]
