# Generated by Django 4.2 on 2024-12-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactos',
            new_name='form_Contactos',
        ),
    ]
