# Generated by Django 4.2 on 2024-12-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_contactos_form_contactos'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_Rrhh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('cv', models.FileField(upload_to='cvs/')),
            ],
        ),
    ]
